MODEL:
  TYPE: cswin
  NAME: cswin_tiny_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./pretrained_ckpt/cswin_tiny_224.pth"
  CSWIN:
    EMBED_DIM: 64
    DEPTH: [ 1, 2, 9, 1 ]
    NUM_HEADS: [ 2, 4, 8, 16 ]
    SPLIT_SIZE: [1, 2, 7, 7]

